# Generated by Django 4.2.5 on 2026-02-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('done', models.BooleanField(default=False)),
                ('date_created', models.DurationField()),
                ('date_completed', models.BooleanField(default=True)),
            ],
        ),
    ]
